### ISSUE TITLE
HOW TO EUN THIS CODE

### ISSUE THREAD

**Issue by sadaqatdev** [xyzzy/smile#2]
please tell me how to run this code , any documentation ?

**Comment by xyzzy** [comment]
The code is a 16-bit real-mode MS-DOS .com file.
.com files have no exec header, they just contain code that is loaded %BP+0100h

You can run it natively under ms-dos or windows XP, or with an emulator like dos-box.

As a service I have prepared a web-based dos-box, you can find it here: https://xyzzy.github.io/smile-media/

Enjoy!
