### ISSUE TITLE
Convert  to dart language 

### ISSUE THREAD

**Issue by sadaqatdev** [xyzzy/smile#3]
how i convert into dart language

**Comment by xyzzy** [comment]
The project was specifically designed and written for 16-bit real-mode x86 instruction set.

If you mean the colourful content, that is written in assembler and not too complicated.
If I have some spare time I will try and modernise that into HTML canvas.

**Comment by xyzzy** [comment]
You can find the HTML5 Canvas version here: [https://xyzzy.github.io/smile/canvas.html](https://xyzzy.github.io/smile/canvas.html).
